name: octoDNS CloudflareProvider
on: [pull_request]

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.load.outputs.json }}
    steps:
    - id: load
      run: |
        {
          echo 'json<<EOF'
          curl -L https://github.com/octodns/octodns/raw/main/.ci-config.json
          echo EOF
        } >> $GITHUB_OUTPUT
  ci:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.config.outputs.json).python_versions_active }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: CI Build
        run: |
          ./script/cibuild
  setup-py:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ fromJson(needs.config.outputs.json).python_version_current }}
          architecture: x64
      - name: CI setup.py
        run: |
          ./script/cibuild-setup-py
